<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function saru_world_help($route_name, RouteMatchInterface $route_match) {

  switch($route_name) {

    case 'help.page.saru_world':
      $output = '';
      $output .= '<h3>' . t('About Saru') . '</h3>';
      $output .= '<p>' . t('This seems ok') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail().
 */
function saru_world_mail($key, &$message, $params) {
  switch ($key) {
    case 'saru_world_log':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('There is an error on your website');
      $message['body'][] = $params['message'];

      break;
  }
}